-- Insert default water brands
INSERT INTO public.brands (name, description, logo_url, is_active) VALUES
('Crystal', 'Nacional', 'https://example.com/logos/crystal.png', true),
('Indaiá', 'Nacional', 'https://example.com/logos/indaia.png', true),
('Bonafont', 'Nacional', 'https://example.com/logos/bonafont.png', true),
('São Lourenço', 'Nacional', 'https://example.com/logos/sao-lourenco.png', true),
('Nestlé Pureza Vital', 'Nacional', 'https://example.com/logos/nestle-pureza-vital.png', true),
('Minalba', 'Nacional', 'https://example.com/logos/minalba.png', true),
('Lindoya', 'Nacional', 'https://example.com/logos/lindoya.png', true),
('Serra Negra', 'Nacional', 'https://example.com/logos/serra-negra.png', true),
('Petrópolis', 'Nacional', 'https://example.com/logos/petropolis.png', true),
('Bioleve', 'Nacional', 'https://example.com/logos/bioleve.png', true),
('Ibirá', 'Regional Sudeste', 'https://example.com/logos/ibira.png', true),
('Levity', 'Regional Sudeste', 'https://example.com/logos/levity.png', true),
('Água Prata', 'Regional Sudeste', 'https://example.com/logos/agua-prata.png', true),
('Ouro Fino', 'Regional Sudeste', 'https://example.com/logos/ouro-fino.png', true),
('Itu', 'Regional Sudeste', 'https://example.com/logos/itu.png', true),
('Fonte Platina', 'Regional Sul', 'https://example.com/logos/fonte-platina.png', true),
('Serra Azul', 'Regional Sul', 'https://example.com/logos/serra-azul.png', true),
('Pureza da Serra', 'Regional Sul', 'https://example.com/logos/pureza-da-serra.png', true),
('Fonte Ijuí', 'Regional Sul', 'https://example.com/logos/fonte-ijui.png', true),
('Fontes de Belém', 'Regional Sul', 'https://example.com/logos/fontes-de-belem.png', true),
('Fresca', 'Regional Nordeste', 'https://example.com/logos/fresca.png', true),
('Santa Clara', 'Regional Nordeste', 'https://example.com/logos/santa-clara.png', true),
('Santa Joana', 'Regional Nordeste', 'https://example.com/logos/santa-joana.png', true),
('Monteiro', 'Regional Nordeste', 'https://example.com/logos/monteiro.png', true),
('Cristal do Sertão', 'Regional Nordeste', 'https://example.com/logos/cristal-do-sertao.png', true),
('Nossa Água', 'Regional Norte', 'https://example.com/logos/nossa-agua.png', true),
('Cristal da Amazônia', 'Regional Norte', 'https://example.com/logos/cristal-amazonia.png', true),
('Fonte Vida', 'Regional Norte', 'https://example.com/logos/fonte-vida.png', true),
('Santa Bárbara Amazônica', 'Regional Norte', 'https://example.com/logos/santa-barbara.png', true),
('Ouro Branco', 'Regional Centro-Oeste', 'https://example.com/logos/ouro-branco.png', true),
('Santa Rita', 'Regional Centro-Oeste', 'https://example.com/logos/santa-rita.png', true),
('Fonte Primavera', 'Regional Centro-Oeste', 'https://example.com/logos/fonte-primavera.png', true),
('Água Mineral Goiás', 'Regional Centro-Oeste', 'https://example.com/logos/agua-mineral-goias.png', true),
('Serra do Roncador', 'Regional Centro-Oeste', 'https://example.com/logos/serra-do-roncador.png', true)
ON CONFLICT DO NOTHING;