// This file is automatically generated.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

// NOTE: Lovable não suporta variáveis VITE_* no front-end publicado.
// Por isso, mantemos a URL e a anon key (publishable) diretamente no código.
const SUPABASE_URL = "https://emeejnoqjvubxysxnmia.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVtZWVqbm9xanZ1Ynh5c3hubWlhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY1NzI4NzUsImV4cCI6MjA4MjE0ODg3NX0.OlsLQATVPstpOMGRQq-TVAmgUbNMwj2Po1xFaOFDMeI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
